version: "3"
services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.11-1.1.0
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "issue-certicate:1:1,Topic2:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
